// ==========================================================================
// HOTEL & ROOM SHOWCASE CONFIGURATION
// Real Property Photos & Exact Room Setups
// Streamlined for instant visitor clarity: Beds, Attached Bath, Kitchen, AC, Hall
// ==========================================================================

const HOTEL_CONFIG = {
  // Brand & Property Details
  name: "Tirupati Cottage",
  type: "Boutique Mountain Cottage & Suites",
  tagline: "Holy Arunachala Mountain & Temple View Stays",
  locationBadge: "Arunachala Mountain View",
  address: "Near Mount Arunachala & Arunachaleswarar Temple, Tiruvannamalai, Tamil Nadu",

  // Location & Google Maps Navigation (Top Priority)
  location: {
    name: "Tiruvannamalai, Tamil Nadu",
    tagline: "Holy Arunachala Mountain & Temple Stays",
    address: "Near Mount Arunachala & Arunachaleswarar Temple, Tiruvannamalai, Tamil Nadu",
    landmark: "S.M.A ILLAM (Black & Gold Arched Gate)",
    mapsUrl: "https://maps.app.goo.gl/2QJHQC5z8egssyQ48?g_st=aw",
    navDriveUrl: "https://www.google.com/maps/dir/?api=1&destination=12.230038,79.077884&travelmode=driving",
    navWalkUrl: "https://www.google.com/maps/dir/?api=1&destination=12.230038,79.077884&travelmode=walking",
    navTempleUrl: "https://www.google.com/maps/dir/Arulmigu+Arunachaleswarar+Temple/12.230038,79.077884",
    navBusStandUrl: "https://www.google.com/maps/dir/Tiruvannamalai+Bus+Stand/12.230038,79.077884",
    coordinates: "12.230038, 79.077884",
    embedUrl: "https://maps.google.com/maps?q=12.230038,79.077884&hl=en&z=15&output=embed"
  },

  // Admin & Booking Contact Details
  admin: {
    name: "Arasu Palani (Owner)",
    phoneDisplay: "+91 75984 30544",
    phoneDial: "+917598430544",
    statusText: "Owner Available"
  },

  // Default language
  defaultLang: "en",

  // Rooms Catalog (Client Exact Inventory with Real Photos)
  rooms: [
    // 1. Single Room 1: 1 bedroom with AC, One kitchen, one bathroom with heater and parking view
    {
      id: "single-room-1",
      name: "Single Room 1 (1 Bed + AC & Kitchen)",
      category: "single",
      categoryLabel: "Single Room",
      badges: ["1 Bed with AC", "Kitchen", "Bath + Heater", "Parking View"],
      price: 2200,
      priceLabel: "₹2,200",
      pricePeriod: "night",
      originalPrice: "₹2,800",
      image: "assets/Single-rooms-2/main-bedroom.jpeg",
      gallery: [
        { src: "assets/Single-rooms-2/main-bedroom.jpeg", title: "AC Bedroom" },
        { src: "assets/Single-rooms-2/kitchen.jpeg", title: "Private Kitchen" },
        { src: "assets/Single-rooms-2/bathroom.jpeg", title: "Bath with Heater" },
        { src: "assets/Single-rooms-2/parking-view.jpeg", title: "Parking View" },
        { src: "assets/Single-rooms-2/porch.jpeg", title: "Entrance Porch" },
        { src: "assets/Single-rooms-2/exterior.jpeg", title: "Building Exterior" }
      ],
      specs: "1–2 Guests • 1 Bedroom with AC • Private Kitchen • Bath with Heater • Parking View",
      beds: "1 Bedroom with Split AC",
      bedsShort: "1 Bed (AC)",
      bathroom: "1 Bathroom (Geyser / Water Heater)",
      bathroomShort: "Bath (Heater)",
      kitchen: "1 Private Kitchen Setup",
      kitchenShort: "Kitchen",
      ac: "Split Inverter AC in Bedroom",
      acShort: "Split AC",
      view: "Parking View",
      translations: {
        ta: {
          name: "சிங்கிள் ரூம் 1 (1 படுக்கை + AC & கிச்சன்)",
          categoryLabel: "சிங்கிள் ரூம்",
          badges: ["1 படுக்கை (AC)", "கிச்சன்", "சுடுநீர் பாத்", "பார்க்கிங் வியூ"],
          specs: "1–2 விருந்தினர்கள் • AC படுக்கையறை • தனி கிச்சன் • சுடுநீர் பாத்ரூம் • பார்க்கிங் காட்சி",
          beds: "1 படுக்கையறை (ஸ்பிளிட் AC உடன்)",
          bedsShort: "1 படுக்கை (AC)",
          bathroom: "1 பாத்ரூம் (சுடுநீர் ஹீட்டர் வசதி)",
          bathroomShort: "சுடுநீர் பாத்",
          kitchen: "1 தனி கிச்சன் வசதி",
          kitchenShort: "கிச்சன்",
          ac: "ஸ்பிளிட் AC படுக்கையறை",
          acShort: "ஸ்பிளிட் AC",
          view: "பார்க்கிங் காட்சி"
        },
        te: {
          name: "సింగిల్ రూమ్ 1 (1 బెడ్ + AC & కిచెన్)",
          categoryLabel: "సింగిల్ రూమ్",
          badges: ["1 బెడ్ (AC)", "కిచెన్", "గీజర్ బాత్", "పార్కింగ్ వ్యూ"],
          specs: "1–2 అతిథులు • AC బెడ్‌రూమ్ • ప్రైవేట్ కిచెన్ • గీజర్ బాత్రూమ్ • పార్కింగ్ వ్యూ",
          beds: "1 బెడ్‌రూమ్ (స్ప్లిట్ AC తో)",
          bedsShort: "1 బెడ్ (AC)",
          bathroom: "1 బాత్రూమ్ (వాటర్ హీటర్ / గీజర్)",
          bathroomShort: "గీజర్ బాత్",
          kitchen: "1 ప్రైవేట్ కిచెన్",
          kitchenShort: "కిచెన్",
          ac: "స్ప్లిట్ AC బెడ్‌రూమ్",
          acShort: "స్ప్లిట్ AC",
          view: "పార్కింగ్ వ్యూ"
        },
        hi: {
          name: "सिंगल रूम 1 (1 बेड + AC व किचन)",
          categoryLabel: "सिंगल रूम",
          badges: ["1 बेड (AC)", "किचन", "गीज़र बाथरूम", "पार्किंग दृश्य"],
          specs: "1–2 मेहमान • AC बेडरूम • प्राइवेट किचन • गीज़र बाथरूम • पार्किंग दृश्य",
          beds: "1 बेडरूम (स्प्लिट AC युक्त)",
          bedsShort: "1 बेड (AC)",
          bathroom: "1 बाथरूम (गीज़र / गर्म पानी)",
          bathroomShort: "गीज़र बाथरूम",
          kitchen: "1 प्राइवेट किचन",
          kitchenShort: "किचन",
          ac: "स्प्लिट AC बेडरूम",
          acShort: "स्प्लिट AC",
          view: "पार्किंग दृश्य"
        },
        kn: {
          name: "ಸಿಂಗಲ್ ರೂಮ್ 1 (1 ಬೆಡ್ + AC & ಕಿಚನ್)",
          categoryLabel: "ಸಿಂಗಲ್ ರೂಮ್",
          badges: ["1 ಬೆಡ್ (AC)", "ಕಿಚನ್", "ಬಿಸಿ ನೀರು ಬಾತ್", "ಪಾರ್ಕಿಂಗ್ ನೋಟ"],
          specs: "1–2 ಅತಿಥಿಗಳು • AC ಬೆಡ್‌ರೂಮ್ • ಪ್ರತ್ಯೇಕ ಕಿಚನ್ • ಬಿಸಿ ನೀರು ಬಾತ್ರೂಮ್ • ಪಾರ್ಕಿಂಗ್ ನೋಟ",
          beds: "1 ಬೆಡ್‌ರೂಮ್ (ಸ್ಪ್ಲಿಟ್ AC ಸಹಿತ)",
          bedsShort: "1 ಬೆಡ್ (AC)",
          bathroom: "1 ಬಾತ್ರೂಮ್ (ಗೀಸರ್ / ಬಿಸಿ ನೀರು)",
          bathroomShort: "ಬಿಸಿ ನೀರು ಬಾತ್",
          kitchen: "1 ಪ್ರತ್ಯೇಕ ಕಿಚನ್",
          kitchenShort: "ಕಿಚನ್",
          ac: "ಸ್ಪ್ಲಿಟ್ AC ಬೆಡ್‌ರೂಮ್",
          acShort: "ಸ್ಪ್ಲಿಟ್ AC",
          view: "ಪಾರ್ಕಿಂಗ್ ನೋಟ"
        },
        ml: {
          name: "സിംഗിൾ റൂം 1 (1 ബെഡ് + AC & കിച്ചൻ)",
          categoryLabel: "സിംഗിൾ റൂം",
          badges: ["1 ബെഡ് (AC)", "കിച്ചൻ", "ഹീറ്റർ ബാത്ത്", "പാർക്കിംഗ് വ്യൂ"],
          specs: "1–2 അതിഥികൾ • AC ബെഡ്‌റൂം • പ്രൈവറ്റ് കിച്ചൻ • ഹീറ്റർ ബാത്ത്‌റൂം • പാർക്കിംഗ് വ്യൂ",
          beds: "1 ബെഡ്‌റൂം (സ്പ്ലിറ്റ് AC സഹിതം)",
          bedsShort: "1 ബെഡ് (AC)",
          bathroom: "1 ബാത്ത്‌റൂം (വാട്ടർ ഹീറ്റർ / ഗീസർ)",
          bathroomShort: "ഹീറ്റർ ബാത്ത്",
          kitchen: "1 പ്രൈവറ്റ് കിച്ചൻ",
          kitchenShort: "കിച്ചൻ",
          ac: "സ്പ്ലിറ്റ് AC ബെഡ്‌റൂം",
          acShort: "സ്പ്ലിറ്റ് AC",
          view: "പാർക്കിംഗ് കാഴ്ച്ച"
        }
      }
    },

    // 2. Single Room 2: hall -> one bedroom -> one bathroom with heater
    {
      id: "single-room-2",
      name: "Single Room 2 (Living Hall + 1 Bed)",
      category: "single",
      categoryLabel: "Single Room with Hall",
      badges: ["Living Hall", "1 Bedroom", "Bath with Heater"],
      price: 2400,
      priceLabel: "₹2,400",
      pricePeriod: "night",
      originalPrice: "₹3,000",
      image: "assets/Triple-Room/main-bedroom.jpeg",
      gallery: [
        { src: "assets/Triple-Room/main-bedroom.jpeg", title: "Private Bedroom with Cot" },
        { src: "assets/Triple-Room/bedroom-2.jpeg", title: "Bedroom Wardrobe Area" },
        { src: "assets/Triple-Room/living-hall.jpeg", title: "Living Hall with Display Shelves" },
        { src: "assets/Triple-Room/bathroom.jpeg", title: "Bath with Water Heater" },
        { src: "assets/Triple-Room/dining-area.jpeg", title: "Dining Archway & Wash Area" },
        { src: "assets/Triple-Room/villa-entrance.jpeg", title: "Private Entrance" }
      ],
      specs: "2 Guests • Spacious Living Hall • 1 Private Bedroom • Bath with Heater",
      hall: "Spacious Living Hall",
      hallShort: "Living Hall",
      beds: "1 Private Bedroom",
      bedsShort: "1 Bed",
      bathroom: "1 Bathroom (Geyser / Water Heater)",
      bathroomShort: "Bath (Heater)",
      translations: {
        ta: {
          name: "சிங்கிள் ரூம் 2 (லிவிங் ஹால் + 1 படுக்கை)",
          categoryLabel: "சிங்கிள் ரூம் & ஹால்",
          badges: ["லிவிங் ஹால்", "1 படுக்கை", "சுடுநீர் பாத்"],
          specs: "2 விருந்தினர்கள் • விசாலமான ஹால் • 1 படுக்கையறை • சுடுநீர் பாத்ரூம்",
          hall: "விசாலமான லிவிங் ஹால்",
          hallShort: "லிவிங் ஹால்",
          beds: "1 தனி படுக்கையறை",
          bedsShort: "1 படுக்கை",
          bathroom: "1 பாத்ரூம் (சுடுநீர் வசதி)",
          bathroomShort: "சுடுநீர் பாத்"
        },
        te: {
          name: "సింగిల్ రూమ్ 2 (లివింగ్ హాల్ + 1 బెడ్)",
          categoryLabel: "సింగిల్ రూమ్ & హాల్",
          badges: ["లివింగ్ హాల్", "1 బెడ్", "గీజర్ బాత్"],
          specs: "2 అతిథులు • విశాలమైన హాల్ • 1 బెడ్‌రూమ్ • గీజర్ బాత్రూమ్",
          hall: "విశాలమైన లివింగ్ హాల్",
          hallShort: "లివింగ్ హాల్",
          beds: "1 ప్రైవేట్ బెడ్‌రూమ్",
          bedsShort: "1 బెడ్",
          bathroom: "1 బాత్రూమ్ (వాటర్ హీటర్ / గీజర్)",
          bathroomShort: "గీజర్ బాత్"
        },
        hi: {
          name: "सिंगल रूम 2 (लिविंग हॉल + 1 बेड)",
          categoryLabel: "सिंगल रूम व हॉल",
          badges: ["लिविंग हॉल", "1 बेड", "गीज़र बाथरूम"],
          specs: "2 मेहमान • विशाल लिविंग हॉल • 1 प्राइवेट बेडरूम • गीज़र बाथरूम",
          hall: "विशाल लिविंग हॉल",
          hallShort: "लिविंग हॉल",
          beds: "1 प्राइवेट बेडरूम",
          bedsShort: "1 बेड",
          bathroom: "1 बाथरूम (गीज़र / गर्म पानी)",
          bathroomShort: "गीज़र बाथरूम"
        },
        kn: {
          name: "ಸಿಂಗಲ್ ರೂಮ್ 2 (ಲಿವಿಂಗ್ ಹಾಲ್ + 1 ಬೆಡ್)",
          categoryLabel: "ಸಿಂಗಲ್ ರೂಮ್ & ಹಾಲ್",
          badges: ["ಲಿವಿಂಗ್ ಹಾಲ್", "1 ಬೆಡ್", "ಬಿಸಿ ನೀರು ಬಾತ್"],
          specs: "2 ಅತಿಥಿಗಳು • ವಿಶಾಲವಾದ ಹಾಲ್ • 1 ಪ್ರತ್ಯೇಕ ಬೆಡ್‌ರೂಮ್ • ಬಿಸಿ ನೀರು ಬಾತ್ರೂಮ್",
          hall: "ವಿಶಾಲವಾದ ಲಿವಿಂಗ್ ಹಾಲ್",
          hallShort: "ಲಿವಿಂಗ್ ಹಾಲ್",
          beds: "1 ಪ್ರತ್ಯೇಕ ಬೆಡ್‌ರೂಮ್",
          bedsShort: "1 ಬೆಡ್",
          bathroom: "1 ಬಾತ್ರೂಮ್ (ಗೀಸರ್ / ಬಿಸಿ ನೀರು)",
          bathroomShort: "ಬಿಸಿ ನೀರು ಬಾತ್"
        },
        ml: {
          name: "സിംഗിൾ റൂം 2 (ലിവിംഗ് ഹാൾ + 1 ബെഡ്)",
          categoryLabel: "സിംഗിൾ റൂം & ഹാൾ",
          badges: ["ലിവിംഗ് ഹാൾ", "1 ബെഡ്", "ഹീറ്റർ ബാത്ത്"],
          specs: "2 അതിഥികൾ • വിശാലമായ ഹാൾ • 1 പ്രൈവറ്റ് ബെഡ്‌റൂം • ഹീറ്റർ ബാത്ത്‌റൂം",
          hall: "വിശാലമായ ലിവിംഗ് ഹാൾ",
          hallShort: "ಲಿವಿംഗ് ಹಾಲ್",
          beds: "1 ಪ್ರൈവറ്റ് ബെಡ್‌റൂം",
          bedsShort: "1 ബെഡ്",
          bathroom: "1 ബാത്ത്‌റൂം (വാട്ടർ ഹീറ്റർ / ഗീസർ)",
          bathroomShort: "ഹീറ്റർ ബാത്ത്"
        }
      }
    },

    // 3. Triple Room: Hall -> 3 bedroom, 3rd room with AC -> 2 bathroom
    {
      id: "triple-room",
      name: "Triple Bedroom Suite (Hall + 3 Beds + 2 Baths)",
      category: "triple",
      categoryLabel: "Triple Bedroom Suite",
      badges: ["Living Hall", "3 Bedrooms", "3rd Room AC", "2 Bathrooms"],
      price: 5500,
      priceLabel: "₹5,500",
      pricePeriod: "night",
      originalPrice: "₹7,000",
      image: "assets/Single-rooms-1/main-bedroom.jpeg",
      gallery: [
        { src: "assets/Single-rooms-1/main-bedroom.jpeg", title: "3rd Bedroom with Split AC" },
        { src: "assets/Single-rooms-1/beds.jpeg", title: "Spacious Bedroom (Double Cots)" },
        { src: "assets/Single-rooms-1/living-hall.jpeg", title: "Grand Living Hall" },
        { src: "assets/Single-rooms-1/bathroom-heater.jpeg", title: "Bathroom 1 (Water Heater)" },
        { src: "assets/Single-rooms-1/bathroom-western.jpeg", title: "Bathroom 2 (Western Style)" },
        { src: "assets/Single-rooms-1/entrance.jpeg", title: "Carved Teak Door Entrance" }
      ],
      specs: "6 Guests • Grand Living Hall • 3 Bedrooms (3rd Room with AC) • 2 Bathrooms",
      hall: "Grand Living Hall",
      hallShort: "Living Hall",
      beds: "3 Bedrooms (3rd Bedroom with AC)",
      bedsShort: "3 Beds (1 AC)",
      bathroom: "2 Full Bathrooms (Hot Water)",
      bathroomShort: "2 Bathrooms",
      ac: "Split AC in 3rd Bedroom",
      acShort: "AC in 3rd Room",
      translations: {
        ta: {
          name: "டிரிபிள் பெட்ரூம் சூட் (ஹால் + 3 படுக்கை + 2 பாத்)",
          categoryLabel: "டிரிபிள் சூட்",
          badges: ["லிவிங் ஹால்", "3 படுக்கை", "3-வது அறை AC", "2 பாத்ரூம்"],
          specs: "6 விருந்தினர்கள் • பெரிய ஹால் • 3 படுக்கையறைகள் (3-வது அறையில் AC) • 2 பாத்ரூம்கள்",
          hall: "பெரிய லிவிங் ஹால்",
          hallShort: "லிவிங் ஹால்",
          beds: "3 படுக்கையறைகள் (3-வது அறை AC உடன்)",
          bedsShort: "3 படுக்கை (1 AC)",
          bathroom: "2 முழு பாத்ரூம்கள் (சுடுநீர்)",
          bathroomShort: "2 பாத்ரூம்",
          ac: "3-வது அறையில் ஸ்பிளிட் AC",
          acShort: "3-வது அறை AC"
        },
        te: {
          name: "ట్రిపుల్ బెడ్‌రూమ్ సూట్ (హాల్ + 3 బెడ్స్ + 2 బాత్స్)",
          categoryLabel: "ట్రిపుల్ సూట్",
          badges: ["లివింగ్ హాల్", "3 బెడ్స్", "3వ గది AC", "2 బాత్రూమ్స్"],
          specs: "6 అతిథులు • గ్రాండ్ లివింగ్ హాల్ • 3 బెడ్‌రూమ్‌లు (3వ గది AC తో) • 2 బాత్రూమ్‌లు",
          hall: "గ్రాండ్ లివింగ్ హాల్",
          hallShort: "లివింగ్ హాల్",
          beds: "3 బెడ్‌రూమ్‌లు (3వ గది AC తో)",
          bedsShort: "3 బెడ్స్ (1 AC)",
          bathroom: "2 పూర్తి బాత్రూమ్‌లు (హాట్ వాటర్)",
          bathroomShort: "2 బాత్రూమ్స్",
          ac: "3వ బెడ్‌రూమ్‌లో స్ప్లిట్ AC",
          acShort: "3వ గది AC"
        },
        hi: {
          name: "ट्रिपल बेडरूम सुइट (हॉल + 3 बेड + 2 बाथरूम)",
          categoryLabel: "ट्रिपल सुइट",
          badges: ["लिविंग हॉल", "3 बेड", "तीसरे कमरे में AC", "2 बाथरूम"],
          specs: "6 मेहमान • बड़ा लिविंग हॉल • 3 बेडरूम (तीसरे कमरे में AC) • 2 बाथरूम",
          hall: "बड़ा लिविंग हॉल",
          hallShort: "लिविंग हॉल",
          beds: "3 बेडरूम (तीसरे बेडरूम में AC)",
          bedsShort: "3 बेड (1 AC)",
          bathroom: "2 बाथरूम (गीज़र / गर्म पानी)",
          bathroomShort: "2 बाथरूम",
          ac: "तीसरे बेडरूम में स्प्लिट AC",
          acShort: "3rd रूम AC"
        },
        kn: {
          name: "ಟ್ರಿಪಲ್ ಬೆಡ್‌ರೂಮ್ ಸೂಟ್ (ಹಾಲ್ + 3 ಬೆಡ್ + 2 ಬಾತ್)",
          categoryLabel: "ಟ್ರಿಪಲ್ ಸೂಟ್",
          badges: ["ಲಿವಿಂಗ್ ಹಾಲ್", "3 ಬೆಡ್", "3ನೇ ಕೋಣೆ AC", "2 ಬಾತ್ರೂಮ್"],
          specs: "6 ಅತಿಥಿಗಳು • ದೊಡ್ಡ ಲಿವಿಂಗ್ ಹಾಲ್ • 3 ಬೆಡ್‌ರೂಮ್‌ಗಳು (3ನೇ ಕೋಣೆ AC ಸಹಿತ) • 2 ಬಾತ್ರೂಮ್‌ಗಳು",
          hall: "ದೊಡ್ಡ ಲಿವಿಂಗ್ ಹಾಲ್",
          hallShort: "ಲಿವಿಂಗ್ ಹಾಲ್",
          beds: "3 ಬೆಡ್‌ರೂಮ್‌ಗಳು (3ನೇ ಕೋಣೆ AC ಸಹಿತ)",
          bedsShort: "3 ಬೆಡ್ (1 AC)",
          bathroom: "2 ಪೂರ್ಣ ಬಾತ್ರೂಮ್‌ಗಳು (ಬಿಸಿ ನೀರು)",
          bathroomShort: "2 ಬಾತ್ರೂಮ್",
          ac: "3ನೇ ಬೆಡ್‌ರೂಮ್‌ನಲ್ಲಿ ಸ್ಪ್ಲಿಟ್ AC",
          acShort: "3ನೇ ಕೋಣೆ AC"
        },
        ml: {
          name: "ട്രിപ്പിൾ ബെഡ്‌റൂം സ്യൂട്ട് (ഹാൾ + 3 ബെഡ് + 2 ബാത്ത്)",
          categoryLabel: "ട്രിപ്പിൾ സ്യൂട്ട്",
          badges: ["ലിവിംഗ് ഹാൾ", "3 ബെഡ്", "3-ാം റൂം AC", "2 ബാത്ത്‌റൂം"],
          specs: "6 അതിഥികൾ • വിശാലമായ ഹാൾ • 3 ബെഡ്‌റൂമുകൾ (3-ാം മുറിയിൽ AC) • 2 ബാത്ത്‌റൂമുകൾ",
          hall: "വിശാലമായ ലിവിംഗ് ഹാൾ",
          hallShort: "ലിവിംഗ് ഹാൾ",
          beds: "3 ബെഡ്‌റൂമുകൾ (3-ാം മുറി AC സഹിതം)",
          bedsShort: "3 ബെഡ് (1 AC)",
          bathroom: "2 മുഴുവൻ ബാത്ത്‌റൂമുകൾ (ചൂടുവെള്ളം)",
          bathroomShort: "2 ബാത്ത്‌റൂം",
          ac: "3-ാം ബെഡ്‌റൂമിൽ സ്പ്ലിറ്റ് AC",
          acShort: "3-ാം റൂം AC"
        }
      }
    }
  ]
};

// ==========================================================================
// MULTI-LANGUAGE TRANSLATIONS
// Supported: English, தமிழ் (Tamil), తెలుగు (Telugu), हिन्दी (Hindi),
//            ಕನ್ನಡ (Kannada), മലയാളം (Malayalam)
// ==========================================================================

const TRANSLATIONS = {
  en: {
    langName: "English",
    langCode: "EN",
    callAdminBtn: "Call to Book",
    heroBadge: "Arunachala Mountain View • Direct Portal",
    heroVistaCaption: "Serene Mountain & Temple View Cottage",
    heroTitle: "Explore Our Rooms",
    heroSubtitle: "Attached Bathroom • Kitchen • Beds • Split AC",
    heroCallBtn: "Call Owner to Book",
    heroHelpline: "Owner:",
    sectionTag: "Accommodations",
    sectionTitle: "Select Your Room",
    sectionSubtitle: "Tap any room to see full photos & facilities",
    filterAll: "All Rooms",
    filterSingle: "Single Rooms",
    filterDouble: "Double Rooms",
    filterTriple: "Triple Rooms",
    callToBook: "Call to Book",
    viewDetails: "View Photos",
    perNight: "/ night",
    hallTitle: "Living Hall",
    kitchenette: "Kitchen",
    fullKitchen: "Kitchen",
    splitAc: "Split AC",
    twoBeds: "2 Beds",
    bedConfig: "Beds",
    attachedBath: "Bathroom",
    kitchenSetup: "Kitchen",
    airConditioning: "Air Conditioning",
    parkingView: "Parking View",
    photosCount: "Photos",
    modalDirectNote: "Direct booking with hotel desk • Zero commission",
    dockCall: "Call Owner to Book",
    locationNavBtn: "Location",
    heroMapBtn: "View on Google Maps",
    locationTag: "Property Location",
    locationTitle: "Arunachala Mountain & Temple Location",
    locationSubtitle: "Conveniently located in Tiruvannamalai with direct views and fast temple access",
    locationAddress: "Near Mount Arunachala & Temple, Tiruvannamalai, Tamil Nadu",
    openGoogleMaps: "Open in Google Maps / Get Directions",
    startNavigation: "Navigate",
    dockMaps: "Directions",
    locHighlight1Title: "Mount Arunachala",
    locHighlight1Desc: "Clear view from stay",
    locHighlight2Title: "Arunachaleswarar Temple",
    locHighlight2Desc: "Close proximity",
    locHighlight3Title: "Girivalam Path",
    locHighlight3Desc: "Ideal for pilgrimage",
    locHighlight4Title: "On-Site Parking",
    locHighlight4Desc: "Safe car & bike parking",
    modalLocationLink: "View Exact Location on Google Maps",
    navHubTitle: "Smart Arrival & Route Navigator",
    navHubSubtitle: "Follow the live turn-by-turn route directly to our gate",
    navModeDrive: "Drive (Car/Bike)",
    navModeWalk: "Walk (Girivalam)",
    navFromTemple: "From Temple (5 mins)",
    navFromBusStand: "From Bus Stand (7 mins)",
    navLiveBtn: "Start Live GPS Navigation",
    landmarkGuideTitle: "Visual Landmark: Spot Our Gate",
    landmarkNameplate: "Look for 'S.M.A ILLAM' Nameplate",
    landmarkFeatures: "Black & gold arched gate with tinted glass facade",
    copyGpsBtn: "Copy GPS",
    gpsCopiedToast: "GPS coordinates copied for driver/maps!",
    lostHelpTitle: "Can't find the street?",
    lostHelpDesc: "Call our desk right now — our staff will guide your auto/car driver turn-by-turn or meet you at the street entrance.",
    lostCallBtn: "Call Desk for Direction Help",
    step1Title: "1. Tap Live Navigate",
    step1Desc: "Turn-by-turn voice & GPS directions on Google Maps",
    step2Title: "2. Near Mountain View",
    step2Desc: "Avenue facing Mount Arunachala",
    step3Title: "3. Spot 'S.M.A ILLAM'",
    step3Desc: "Look for black & gold arched gate",
    step4Title: "4. Safe On-Site Parking",
    step4Desc: "Drive straight into private parking",
    landmarkDriverTip: "Show this building gate photo to your auto / taxi driver",
    viewGatePhoto: "View Gate Photo Full Screen"
  },

  ta: {
    langName: "தமிழ்",
    langCode: "தமி",
    callAdminBtn: "புக் செய்ய அழை",
    heroBadge: "நேரடி விருந்தினர் • ஆன்லைன்",
    heroVistaCaption: "அருணாசல மலை & கோவில் காட்சி காட்டேஜ்",
    heroTitle: "அறைகளை பாருங்கள்",
    heroSubtitle: "அட்டாச்ட் பாத்ரூம் • கிச்சன் • படுக்கை • ஸ்பிளிட் AC",
    heroCallBtn: "உரிமையாளரை அழைக்கவும்",
    heroHelpline: "உரிமையாளர்:",
    sectionTag: "தங்கும் அறைகள்",
    sectionTitle: "அறையைத் தேர்ந்தெடுங்கள்",
    sectionSubtitle: "படங்கள் & வசதிகளைப் பார்க்க அறையைத் தட்டவும்",
    filterAll: "அனைத்து அறைகள்",
    filterSingle: "சிங்கிள் ரூம்",
    filterDouble: "டபுள் ரூம்",
    filterTriple: "டிரிபிள் ரூம்",
    callToBook: "அழைக்கவும்",
    viewDetails: "படங்கள் பார்க்க",
    perNight: "/ இரவு",
    hallTitle: "லிவிங் ஹால்",
    kitchenette: "கிச்சன்",
    fullKitchen: "கிச்சன்",
    splitAc: "ஸ்பிளிட் AC",
    twoBeds: "2 படுக்கை",
    bedConfig: "படுக்கை",
    attachedBath: "பாத்ரூம்",
    kitchenSetup: "கிச்சன்",
    airConditioning: "ஸ்பிளிட் AC",
    parkingView: "பார்க்கிங் காட்சி",
    photosCount: "படங்கள்",
    modalDirectNote: "நேரடி முன்பதிவு • கமிஷன் கட்டணம் இல்லை",
    dockCall: "உரிமையாளரை அழைக்கவும்",
    locationNavBtn: "இருப்பிடம்",
    heroMapBtn: "Google Maps-ல் பார்க்க",
    locationTag: "ஹோட்டல் இருப்பிடம்",
    locationTitle: "அருணாசல மலை & கோவில் இருப்பிடம்",
    locationSubtitle: "திருவண்ணாமலையில் நேரடி மலைக் காட்சி மற்றும் எளிதான கோவில் அணுகலுடன் அமைந்துள்ளது",
    locationAddress: "அருணாசல மலை & கோவில் அருகில், திருவண்ணாமலை, தமிழ்நாடு",
    openGoogleMaps: "Google Maps-ல் வழித்தடம் பெற",
    startNavigation: "வழித்தடம்",
    dockMaps: "வரைபடம்",
    locHighlight1Title: "அருணாசல மலை",
    locHighlight1Desc: "நேரடி மலைக் காட்சி",
    locHighlight2Title: "அருணாசலேஸ்வரர் கோவில்",
    locHighlight2Desc: "எளிதான கோவில் அணுகல்",
    locHighlight3Title: "கிரிவலப் பாதை",
    locHighlight3Desc: "பக்தர்களுக்கு ஏற்றது",
    locHighlight4Title: "பாதுகாப்பான பார்க்கிங்",
    locHighlight4Desc: "கார் & பைக் பார்க்கிங் வசதி",
    modalLocationLink: "Google Maps-ல் இருப்பிடம் பார்க்க",
    navHubTitle: "நேரடி வழித்தடம் & இருப்பிட வழிகாட்டி",
    navHubSubtitle: "எங்கள் வாயில் வரை நேரடி திருப்ப வழித்தடத்தைப் பின்பற்றுங்கள்",
    navModeDrive: "வாகனம் (கார் / பைக்)",
    navModeWalk: "நடந்து செல்ல (கிரிவலம்)",
    navFromTemple: "கோவிலிலிருந்து (5 நிமி)",
    navFromBusStand: "பேருந்து நிலையத்திலிருந்து (7 நிமி)",
    navLiveBtn: "நேரடி GPS வழிகாட்டலைத் தொடங்கு",
    landmarkGuideTitle: "கட்டிட அடையாளம்: நுழைவாயில்",
    landmarkNameplate: "'S.M.A ILLAM' பெயர் பலகையைப் பாருங்கள்",
    landmarkFeatures: "கருப்பு & தங்க வளைவு கேட், வண்ணக் கண்ணாடி முகப்பு",
    copyGpsBtn: "GPS நகலெடு",
    gpsCopiedToast: "GPS குறியீடு நகலெடுக்கப்பட்டது!",
    lostHelpTitle: "தெருவைக் கண்டுபிடிக்க முடியவில்லையா?",
    lostHelpDesc: "உடனே அழைக்கவும் — எங்கள் ஊழியர்கள் உங்கள் டிரைவருக்கு திருப்பத்திற்கு திருப்பம் வழி காட்டுவார்கள்.",
    lostCallBtn: "வழிகாட்டுதலுக்கு அழைக்கவும்",
    step1Title: "1. வழித்தடத்தைத் தொடங்கு",
    step1Desc: "Google Maps-ல் நேரடி திருப்ப GPS வழிகாட்டல்",
    step2Title: "2. மலைக் காட்சி அருகில்",
    step2Desc: "அருணாசல மலையை நோக்கிய சாலை",
    step3Title: "3. 'S.M.A ILLAM' வாயில்",
    step3Desc: "கருப்பு & தங்க வளைவு கேட்டைப் பாருங்கள்",
    step4Title: "4. பாதுகாப்பான பார்க்கிங்",
    step4Desc: "நேரடியாக வளாகத்திற்குள் வாகனத்தை நிறுத்தலாம்",
    landmarkDriverTip: "இந்த நுழைவாயில் புகைப்படத்தை உங்கள் ஆட்டோ / கார் டிரைவரிடம் காட்டவும்",
    viewGatePhoto: "நுழைவாயில் புகைப்படத்தைப் பெரிதாகப் பார்க்க"
  },

  te: {
    langName: "తెలుగు",
    langCode: "తెలు",
    callAdminBtn: "బుక్ చేయడానికి కాల్",
    heroBadge: "డైరెక్ట్ గెస్ట్ • ఆన్‌లైన్",
    heroVistaCaption: "అరుణాచల పర్వతం & ఆలయ వ్యూ రిసార్ట్",
    heroTitle: "గదులు చూడండి",
    heroSubtitle: "అటాచ్డ్ బాత్రూమ్ • కిచెన్ • బెడ్స్ • స్ప్లిట్ AC",
    heroCallBtn: "బుక్ చేయడానికి కాల్ చేయండి",
    heroHelpline: "రిజర్వేషన్లు:",
    sectionTag: "వసతులు",
    sectionTitle: "మీ గదిని ఎంచుకోండి",
    sectionSubtitle: "ఫోటోలు & వివరాలు చూడటానికి గదిపై ట్యాప్ చేయండి",
    filterAll: "అన్ని గదులు",
    filterSingle: "సింగిల్ రూమ్స్",
    filterDouble: "డబుల్ రూమ్స్",
    filterTriple: "ట్రిపుల్ రూమ్స్",
    callToBook: "కాల్ చేయండి",
    viewDetails: "ఫోటోలు చూడండి",
    perNight: "/ రాత్రి",
    hallTitle: "లివింగ్ హాల్",
    kitchenette: "కిచెన్",
    fullKitchen: "కిచెన్",
    splitAc: "స్ప్లిట్ AC",
    twoBeds: "2 బెడ్స్",
    bedConfig: "బెడ్స్",
    attachedBath: "బాత్రూమ్",
    kitchenSetup: "కిచెన్",
    airConditioning: "స్ప్లిట్ AC",
    parkingView: "పార్కింగ్ వ్యూ",
    photosCount: "ఫోటోలు",
    modalDirectNote: "డైరెక్ట్ బుకింగ్ • జీరో కమిషన్ ఫీజు",
    dockCall: "బుక్ చేయడానికి కాల్ చేయండి",
    locationNavBtn: "లొకేషన్",
    heroMapBtn: "Google Maps లో చూడండి",
    locationTag: "ప్రాపర్టీ లొకేషన్",
    locationTitle: "అరుణాచల పర్వతం & ఆలయ లొకేషన్",
    locationSubtitle: "తిరువణ్ణామలైలో పర్వత దృశ్యం మరియు ఆలయ సమీపంలో ఉంది",
    locationAddress: "అరుణాచల పర్వతం & ఆలయం సమీపంలో, తిరువణ్ణామలై, తమిళనాడు",
    openGoogleMaps: "Google Maps లో మార్గం చూడండి",
    startNavigation: "నావిగేట్ చేయండి",
    dockMaps: "దిశలు",
    locHighlight1Title: "అరుణాచల పర్వతం",
    locHighlight1Desc: "ప్రత్యక్ష పర్వత దృశ్యం",
    locHighlight2Title: "అరుణాచలేశ్వర ఆలయం",
    locHighlight2Desc: "త్వరిత ఆలయ ప్రవేశం",
    locHighlight3Title: "గిరివల ప్రదక్షిణ",
    locHighlight3Desc: "భక్తులకు అనుకూలం",
    locHighlight4Title: "సురక్షిత పార్కింగ్",
    locHighlight4Desc: "కార్ & బైక్ పార్కింగ్",
    modalLocationLink: "Google Maps లో లొకేషన్ చూడండి",
    navHubTitle: "లైవ్ రూట్ నావిగేటర్",
    navHubSubtitle: "మా గేట్ వరకు లైవ్ టర్న్-బై-టర్న్ రూట్‌ను అనుసరించండి",
    navModeDrive: "వాహనం (కార్ / బైక్)",
    navModeWalk: "నడక (గిరివల)",
    navFromTemple: "ఆలయం నుండి (5 నిమి)",
    navFromBusStand: "బస్ స్టాండ్ నుండి (7 నిమి)",
    navLiveBtn: "లైవ్ GPS నావిగేషన్ ప్రారంభించండి",
    landmarkGuideTitle: "ల్యాండ్‌మార్క్ గైడ్",
    landmarkNameplate: "'S.M.A ILLAM' నేమ్‌ప్లేట్ చూడండి",
    landmarkFeatures: "నలుపు & బంగారు తోరణం గేట్, గాజు ముఖభాగం",
    copyGpsBtn: "GPS కాపీ",
    gpsCopiedToast: "GPS కోఆర్డినేట్స్ కాపీ చేయబడ్డాయి!",
    lostHelpTitle: "దారి దొరకలేదా?",
    lostHelpDesc: "మా డెస్క్‌కి కాల్ చేయండి — డ్రైవర్‌కి నేరుగా దారి వివరిస్తాము.",
    lostCallBtn: "రూట్ సహాయం కోసం కాల్ చేయండి",
    step1Title: "1. నావిగేషన్ ప్రారంభించండి",
    step1Desc: "Google Maps టర్న్-బై-టర్న్ GPS మార్గం",
    step2Title: "2. పర్వత దృశ్యం సమీపంలో",
    step2Desc: "అరుణాచల పర్వతం ఎదురుగా ఉన్న వీధి",
    step3Title: "3. 'S.M.A ILLAM' గుర్తు",
    step3Desc: "నలుపు & బంగారు తోరణ గేటును చూడండి",
    step4Title: "4. సురಕ್ಷిత పార్కింగ్",
    step4Desc: "నేరుగా కాంప్లెక్స్ లోపల పార్క్ చేయండి",
    landmarkDriverTip: "ఈ గేటు ఫోటోను మీ ఆటో / టాక్సీ డ్రైవర్‌కు చూపించండి",
    viewGatePhoto: "గేటు ఫోటోను పెద్దదిగా చూడండి"
  },

  hi: {
    langName: "हिन्दी",
    langCode: "हिन्",
    callAdminBtn: "बुक करने हेतु कॉल",
    heroBadge: "डायरेक्ट पोर्टल • ऑनलाइन",
    heroVistaCaption: "अरुणाचल पर्वत व मंदिर दृश्य रिज़ॉर्ट",
    heroTitle: "हमारे कमरे देखें",
    heroSubtitle: "अटैच्ड बाथरूम • किचन • बेड • स्प्लिट AC",
    heroCallBtn: "एडमिन को कॉल करें",
    heroHelpline: "बुकिंग सहायता:",
    sectionTag: "कमरे व सुइट",
    sectionTitle: "अपना कमरा चुनें",
    sectionSubtitle: "तस्वीरें व सुविधाएं देखने के लिए कमरे पर टैप करें",
    filterAll: "सभी कमरे",
    filterSingle: "सिंगल रूम",
    filterDouble: "डबल रूम",
    filterTriple: "ट्रिपल रूम",
    callToBook: "कॉल करें",
    viewDetails: "तस्वीरें देखें",
    perNight: "/ रात",
    hallTitle: "लिविंग हॉल",
    kitchenette: "किचन",
    fullKitchen: "किचन",
    splitAc: "स्प्लिट AC",
    twoBeds: "2 बेड",
    bedConfig: "बेड",
    attachedBath: "बाथरूम",
    kitchenSetup: "किचन",
    airConditioning: "स्प्लिट AC",
    parkingView: "पार्किंग दृश्य",
    photosCount: "तस्वीरें",
    modalDirectNote: "सीधी बुकिंग • शून्य कमीशन शुल्क",
    dockCall: "एडमिन को कॉल करें",
    locationNavBtn: "लोकेशन",
    heroMapBtn: "Google Maps पर देखें",
    locationTag: "होटल लोकेशन",
    locationTitle: "अरुणाचल पर्वत व मंदिर लोकेशन",
    locationSubtitle: "तिरुवन्नामलाई में मंदिर व पर्वत दृश्य के समीप सुविधाजनक स्थान",
    locationAddress: "अरुणाचल पर्वत व मंदिर के पास, तिरुवन्नामलाई, तमिलनाडु",
    openGoogleMaps: "Google Maps पर दिशा-निर्देश पाएं",
    startNavigation: "नेविगेट करें",
    dockMaps: "दिशा-निर्देश",
    locHighlight1Title: "अरुणाचल पर्वत",
    locHighlight1Desc: "प्रत्यक्ष पर्वत दृश्य",
    locHighlight2Title: "अरुणाचलेश्वर मंदिर",
    locHighlight2Desc: "आसान मंदिर पहुंच",
    locHighlight3Title: "गिरिवलम मार्ग",
    locHighlight3Desc: "भक्तों के लिए उत्तम",
    locHighlight4Title: "सुरक्षित पार्किंग",
    locHighlight4Desc: "कार व बाइक पार्किंग",
    modalLocationLink: "Google Maps पर लोकेशन देखें",
    navHubTitle: "लाइव रूट व दिशा-निर्देश",
    navHubSubtitle: "हमारे गेट तक सीधे टर्न-बाय-टर्न मार्ग का अनुसरण करें",
    navModeDrive: "ड्राइव (कार / बाइक)",
    navModeWalk: "पैदल (गिरिवलम)",
    navFromTemple: "मंदिर से (5 मिनट)",
    navFromBusStand: "बस स्टैंड से (7 मिनट)",
    navLiveBtn: "लाइव GPS नेविगेशन शुरू करें",
    landmarkGuideTitle: "भवन पहचान गाइड",
    landmarkNameplate: "'S.M.A ILLAM' नेमप्लेट देखें",
    landmarkFeatures: "काले व सुनहरे मेहराबदार गेट, कांच का मुखौटा",
    copyGpsBtn: "GPS कॉपी करें",
    gpsCopiedToast: "GPS निर्देशांक कॉपी हो गए!",
    lostHelpTitle: "गली नहीं मिल रही?",
    lostHelpDesc: "तुरंत रिसेप्शन पर कॉल करें — हम ड्राइवर को सीधा रास्ता बताएंगे।",
    lostCallBtn: "रास्ते में मदद हेतु कॉल करें",
    step1Title: "1. नेविगेशन शुरू करें",
    step1Desc: "Google Maps पर लाइव टर्न-बाय-टर्न GPS दिशा-निर्देश",
    step2Title: "2. पर्वत दृश्य के पास",
    step2Desc: "अरुणाचल पर्वत के सामने वाली शांत सड़क",
    step3Title: "3. 'S.M.A ILLAM' पहचानें",
    step3Desc: "काले व सुनहरे मेहराबदार गेट को देखें",
    step4Title: "4. सुरक्षित इन-हाउस पार्किंग",
    step4Desc: "सीधे अंदर परिसर में सुरक्षित पार्क करें",
    landmarkDriverTip: "यह गेट की फोटो अपने ऑटो / कैब ड्राइवर को दिखाएं",
    viewGatePhoto: "गेट की फोटो बड़ी करके देखें"
  },

  kn: {
    langName: "ಕನ್ನಡ",
    langCode: "ಕನ್ನ",
    callAdminBtn: "ಬುಕ್ ಮಾಡಲು ಕರೆ",
    heroBadge: "ನೇರ ಪೋರ್ಟಲ್ • ಆನ್‌ಲೈನ್",
    heroVistaCaption: "ಅರುಣಾಚಲ ಪರ್ವತ & ದೇವಾಲಯ ನೋಟ ರೆಸಾರ್ಟ್",
    heroTitle: "ನಮ್ಮ ಕೊಠಡಿಗಳನ್ನು ನೋಡಿ",
    heroSubtitle: "ಅಟಾಚ್ಡ್ ಬಾತ್ರೂಮ್ • ಕಿಚನ್ • ಬೆಡ್ಸ್ • ಸ್ಪ್ಲಿಟ್ AC",
    heroCallBtn: "ಬುಕ್ ಮಾಡಲು ಕರೆ ಮಾಡಿ",
    heroHelpline: "ಕಾಯ್ದಿರಿಸುವಿಕೆ:",
    sectionTag: "ವಸತಿಗಳು",
    sectionTitle: "ನಿಮ್ಮ ಕೊಠಡಿ ಆಯ್ಕೆಮಾಡಿ",
    sectionSubtitle: "ಫೋಟೋಗಳು & ಸೌಲಭ್ಯಗಳನ್ನು ನೋಡಲು ಕೊಠಡಿ ಮೇಲೆ ಟ್ಯಾಪ್ ಮಾಡಿ",
    filterAll: "ಎಲ್ಲಾ ಕೊಠಡಿಗಳು",
    filterSingle: "ಸಿಂಗಲ್ ರೂಮ್ಸ್",
    filterDouble: "ಡಬಲ್ ರೂಮ್ಸ್",
    filterTriple: "ಟ್ರಿಪಲ್ ರೂಮ್ಸ್",
    callToBook: "ಕರೆ ಮಾಡಿ",
    viewDetails: "ಫೋಟೋಗಳು ನೋಡಿ",
    perNight: "/ ರಾತ್ರಿ",
    hallTitle: "ಲಿವಿಂಗ್ ಹಾಲ್",
    kitchenette: "ಕಿಚನ್",
    fullKitchen: "ಕಿಚನ್",
    splitAc: "ಸ್ಪ್ಲಿಟ್ AC",
    twoBeds: "2 ಬೆಡ್",
    bedConfig: "ಬೆಡ್",
    attachedBath: "ಬಾತ್ರೂಮ್",
    kitchenSetup: "ಕಿಚನ್",
    airConditioning: "ಸ್ಪ್ಲಿಟ್ AC",
    parkingView: "ಪಾರ್ಕಿಂಗ್ ನೋಟ",
    photosCount: "ಫೋಟೋಗಳು",
    modalDirectNote: "ನೇರ ಬುಕಿಂಗ್ • ಶೂನ್ಯ ಕಮಿಷನ್ ಶುಲ್ಕ",
    dockCall: "ಬುಕ್ ಮಾಡಲು ಕರೆ ಮಾಡಿ",
    locationNavBtn: "ಸ್ಥಳ",
    heroMapBtn: "Google Maps ನಲ್ಲಿ ವೀಕ್ಷಿಸಿ",
    locationTag: "ಹೋಟೆಲ್ ಸ್ಥಳ",
    locationTitle: "ಅರುಣಾಚಲ ಪರ್ವತ & ದೇವಾಲಯ ಸ್ಥಳ",
    locationSubtitle: "ತಿರುವಣ್ಣಾಮಲೈನಲ್ಲಿ ಪರ್ವತ ನೋಟ ಮತ್ತು ದೇವಾಲಯದ ಸಮೀಪದಲ್ಲಿದೆ",
    locationAddress: "ಅರುಣಾಚಲ ಪರ್ವತ & ದೇವಾಲಯದ ಬಳಿ, ತಿರುವಣ್ಣಾಮಲೈ, ತಮಿಳುನಾಡು",
    openGoogleMaps: "Google Maps ನಲ್ಲಿ ದಾರಿ ಪಡೆಯಿರಿ",
    startNavigation: "ನ್ಯಾವಿಗೇಟ್",
    dockMaps: "ದಾರಿ",
    locHighlight1Title: "ಅರುಣಾಚಲ ಪರ್ವತ",
    locHighlight1Desc: "ನೇರ ಪರ್ವತ ನೋಟ",
    locHighlight2Title: "ಅರುಣಾಚಲೇಶ್ವರ ದೇವಾಲಯ",
    locHighlight2Desc: "ಸುಲಭ ದೇವಾಲಯ ಪ್ರವೇಶ",
    locHighlight3Title: "ಗಿರಿವಲಂ ಮಾರ್ಗ",
    locHighlight3Desc: "ಭಕ್ತರಿಗೆ ಸೂಕ್ತವಾಗಿದೆ",
    locHighlight4Title: "ಸುರಕ್ಷಿತ ಪಾರ್ಕಿಂಗ್",
    locHighlight4Desc: "ಕಾರ್ & ಬೈಕ್ ಪಾರ್ಕಿಂಗ್",
    modalLocationLink: "Google Maps ನಲ್ಲಿ ಸ್ಥಳ ವೀಕ್ಷಿಸಿ",
    navHubTitle: "ಲೈವ್ ರೂಟ್ ನ್ಯಾವಿಗೇಟರ್",
    navHubSubtitle: "ನಮ್ಮ ಗೇಟ್‌ವರೆಗೂ ಲೈವ್ ಟರ್ನ್-ಬೈ-ಟರ್ನ್ ದಾರಿಯನ್ನು ಅನುಸರಿಸಿ",
    navModeDrive: "ಡ್ರೈವ್ (ಕಾರು / ಬೈಕ್)",
    navModeWalk: "ನಡಿಗೆ (ಗಿರಿವಲಂ)",
    navFromTemple: "ದೇವಾಲಯದಿಂದ (5 ನಿಮಿ)",
    navFromBusStand: "ಬಸ್ ನಿಲ್ದಾಣದಿಂದ (7 ನಿಮಿ)",
    navLiveBtn: "ಲೈವ್ GPS ನ್ಯಾವಿಗೇಶನ್ ಪ್ರಾರಂಭಿಸಿ",
    landmarkGuideTitle: "ಕಟ್ಟಡದ ಗುರುತು",
    landmarkNameplate: "'S.M.A ILLAM' ನೇಮ್‌ಪ್ಲೇಟ್ ನೋಡಿ",
    landmarkFeatures: "ಕಪ್ಪು & ಚಿನ್ನದ ಕಮಾನು ಗೇಟ್, ಗ್ಲಾಸ್ ಮುಂಭಾಗ",
    copyGpsBtn: "GPS ನಕಲಿಸಿ",
    gpsCopiedToast: "GPS ನಕಲಿಸಲಾಗಿದೆ!",
    lostHelpTitle: "ದಾರಿ ಸಿಗುತ್ತಿಲ್ಲವೇ?",
    lostHelpDesc: "ತಕ್ಷಣ ಕರೆ ಮಾಡಿ — ನಿಮ್ಮ ಚಾಲಕನಿಗೆ ಸರಿಯಾದ ದಾರಿ ತಿಳಿಸುತ್ತೇವೆ.",
    lostCallBtn: "ದಾರಿ ಸಹಾಯಕ್ಕಾಗಿ ಕರೆ ಮಾಡಿ",
    step1Title: "1. ನ್ಯಾವಿಗೇಶನ್ ಪ್ರಾರಂಭಿಸಿ",
    step1Desc: "Google Maps ನಲ್ಲಿ ಲೈವ್ ಟರ್ನ್-ಬೈ-ಟರ್ನ್ GPS ದಾರಿ",
    step2Title: "2. ಪರ್ವತ ನೋಟದ ಹತ್ತಿರ",
    step2Desc: "ಅರುಣಾಚಲ ಪರ್ವತದ ಎದುರಿನ ಶಾಂತ ರಸ್ತೆ",
    step3Title: "3. 'S.M.A ILLAM' ಗುರುತು",
    step3Desc: "ಕಪ್ಪು & ಚಿನ್ನದ ಕಮಾನು ಗೇಟ್ ಗಮನಿಸಿ",
    step4Title: "4. ಸುರಕ್ಷಿತ ಪಾರ್ಕಿಂಗ್",
    step4Desc: "ನೇರವಾಗಿ ಆವರಣದೊಳಗೆ ಪಾರ್ಕ್ ಮಾಡಿ",
    landmarkDriverTip: "ಈ ಗೇಟ್ ಫೋಟೋವನ್ನು ನಿಮ್ಮ ಆಟೋ / ಟ್ಯಾಕ್ಸಿ ಚಾಲಕರಿಗೆ ತೋರಿಸಿ",
    viewGatePhoto: "ಗೇಟ್ ಫೋಟೋ ದೊಡ್ಡದಾಗಿ ವೀಕ್ಷಿಸಿ"
  },

  ml: {
    langName: "മലയാളം",
    langCode: "മല",
    callAdminBtn: "ബുക്ക് ചെയ്യാൻ വിളിക്കുക",
    heroBadge: "ഡയറക്റ്റ് പോർട്ടൽ • ഓൺലൈൻ",
    heroVistaCaption: "അരുണാചല മല & ക്ഷേത്ര കാഴ്ച്ച റിസോർട്ട്",
    heroTitle: "മുറികൾ കാണുക",
    heroSubtitle: "അറ്റാച്ച്ഡ് ബാത്ത്റൂം • കിച്ചൻ • ബെഡ്സ് • സ്പ്ലിറ്റ് AC",
    heroCallBtn: "അഡ്മിനെ വിളിക്കുക",
    heroHelpline: "റിസർവേഷൻ:",
    sectionTag: "താമസസൗകര്യങ്ങൾ",
    sectionTitle: "നിങ്ങളുടെ മുറി തിരഞ്ഞെടുക്കൂ",
    sectionSubtitle: "ഫോട്ടോകളും വിവരങ്ങളും കാണാൻ മുറിയിൽ ക്ലിക്ക് ചെയ്യുക",
    filterAll: "എല്ലാ മുറികളും",
    filterSingle: "സിംഗിൾ റൂംസ്",
    filterDouble: "ഡബിൾ റൂംസ്",
    filterTriple: "ട്രിപ്പിൾ റൂംസ്",
    callToBook: "വിളിക്കുക",
    viewDetails: "ഫോട്ടോകൾ കാണുക",
    perNight: "/ രാത്രി",
    hallTitle: "ലിവിംഗ് ഹാൾ",
    kitchenette: "കിച്ചൻ",
    fullKitchen: "കിച്ചൻ",
    splitAc: "സ്പ്ലിറ്റ് AC",
    twoBeds: "2 ബെഡ്",
    bedConfig: "ബെഡ്",
    attachedBath: "ബാത്ത്‌റൂം",
    kitchenSetup: "കിച്ചൻ",
    airConditioning: "സ്പ്ലിറ്റ് AC",
    parkingView: "പാർക്കിംഗ് കാഴ്ച്ച",
    photosCount: "ഫോട്ടോകൾ",
    modalDirectNote: "നേരിട്ടുള്ള ബുക്കിംഗ് • കമ്മീഷൻ നിരക്കുകളില്ല",
    dockCall: "അഡ്മിനെ വിളിക്കുക",
    locationNavBtn: "ലൊക്കേഷൻ",
    heroMapBtn: "Google Maps-ൽ കാണുക",
    locationTag: "ഹോട്ടൽ ലൊക്കേഷൻ",
    locationTitle: "അരുണാചല മല & ക്ഷേത്ര ലൊക്കേഷൻ",
    locationSubtitle: "തിരുവണ്ണാമലയിൽ മലയുടെ കാഴ്ച്ചയും ക്ഷേത്ര സാമീപ്യവുമുള്ള സ്ഥലം",
    locationAddress: "അരുണാചല മല & ക്ഷേത്രത്തിന് സമീപം, തിരുവണ്ണാമല, തമിഴ്നാട്",
    openGoogleMaps: "Google Maps-ൽ റൂട്ട് കാണുക",
    startNavigation: "നാവിഗേറ്റ് ചെയ്യുക",
    dockMaps: "വഴികൾ",
    locHighlight1Title: "അരുണാചല മല",
    locHighlight1Desc: "നേരിട്ടുള്ള മല കാഴ്ച്ച",
    locHighlight2Title: "അരുണാചലേശ്വര ക്ഷേത്രം",
    locHighlight2Desc: "എളുപ്പത്തിൽ ക്ഷേത്രത്തിൽ എത്താം",
    locHighlight3Title: "ഗിരിവലം വഴി",
    locHighlight3Desc: "തീർത്ഥാടകർക്ക് അനുയോജ്യം",
    locHighlight4Title: "സുരക്ഷിത പാർക്കിംഗ്",
    locHighlight4Desc: "കാർ & ബൈക്ക് പാർക്കിംഗ്",
    modalLocationLink: "Google Maps-ൽ ലൊക്കേഷൻ കാണുക",
    navHubTitle: "ലൈവ് റൂട്ട് നാവിഗേഷൻ",
    navHubSubtitle: "ഞങ്ങളുടെ ഗേറ്റ് വരെ കൃത്യമായ ടേൺ-ബൈ-ടേൺ വഴി പിന്തുടരുക",
    navModeDrive: "ഡ്രൈവ് (കാർ / ബൈക്ക്)",
    navModeWalk: "നടത്തം (ഗിരിവലം)",
    navFromTemple: "ക്ഷേത്രത്തിൽ നിന്ന് (5 മിനിറ്റ്)",
    navFromBusStand: "ബസ് സ്റ്റാൻഡിൽ നിന്ന് (7 മിനിറ്റ്)",
    navLiveBtn: "ലൈവ് GPS നാവിഗേഷൻ ആരംഭിക്കുക",
    landmarkGuideTitle: "കെട്ടിടം തിരിച്ചറിയാൻ",
    landmarkNameplate: "'S.M.A ILLAM' നെയിംപ്ലേറ്റ് കാണുക",
    landmarkFeatures: "കറുപ്പും സ്വർണ്ണ നിറത്തിലുമുള്ള ആർച്ച് ഗേറ്റ്, ഗ്ലാസ് ഫ്രണ്ട്",
    copyGpsBtn: "GPS കോപ്പി ചെയ്യുക",
    gpsCopiedToast: "GPS കോപ്പി ചെയ്തു!",
    lostHelpTitle: "വഴി കണ്ടെത്താൻ കഴിയുന്നില്ലേ?",
    lostHelpDesc: "ഉടൻ വിളിക്കൂ — ഞങ്ങളുടെ ജീവനക്കാർ ഡ്രൈവർക്ക് വഴി നിർദ്ദേശിക്കും.",
    lostCallBtn: "റൂട്ട് സഹായത്തിനായി വിളിക്കുക",
    step1Title: "1. നാവിഗേഷൻ തുടങ്ങുക",
    step1Desc: "Google Maps-ൽ ടേൺ-ബൈ-ടേൺ ലൈവ് GPS റൂട്ട്",
    step2Title: "2. മല കാഴ്ച്ചയ്ക്ക് അടുത്ത്",
    step2Desc: "അരുണാചല മലയ്ക്ക് അഭിമുഖമായ റോഡ്",
    step3Title: "3. 'S.M.A ILLAM' ഗേറ്റ്",
    step3Desc: "കറുപ്പും സ്വർണ്ണ നിറത്തിലുമുള്ള ആർച്ച് ഗേറ്റ്",
    step4Title: "4. സുരക്ഷിത പാർക്കിംഗ്",
    step4Desc: "നേരിട്ട് ഗേറ്റിനുള്ളിൽ പാർക്ക് ചെയ്യാം",
    landmarkDriverTip: "ഈ ഗേറ്റ് ഫോട്ടോ നിങ്ങളുടെ ഓട്ടോ / ടാക്സി ഡ്രൈവർക്ക് കാണിക്കുക",
    viewGatePhoto: "ഗേറ്റ് ഫോട്ടോ വലുതായി കാണുക"
  }
};

window.HOTEL_CONFIG = HOTEL_CONFIG;
window.TRANSLATIONS = TRANSLATIONS;
